"""Installer telemetry — pre-boot install reports.

The installer ISO POSTs to /api/install/report BEFORE the installed system
has ever checked in. This gives Central Command visibility into:
  - Which physical boxes started installing
  - Which completed successfully
  - Which failed, and where
  - Hardware fingerprint (BIOS, drive, RAM) per appliance

Round Table Session 205: pre-boot telemetry catches silent failures
(zombie daemon, drive corruption, network issues) before customers notice.

Security model: installer authenticates with a shared secret (INSTALL_TOKEN
environment variable). Installer embeds this in the ISO build. Not a strong
secret — the installer ISO is effectively public to anyone with physical
access — but sufficient to reject internet-wide noise.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from .auth import require_auth
from .shared import execute_with_retry, get_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/install", tags=["install"])


# Shared secret auth — ISO embeds this at build time.
# Default value is intentionally recognizable so a misconfigured deployment
# is obvious. Production ISOs must be built with a real secret.
INSTALL_TOKEN = os.getenv("INSTALL_TOKEN", "osiriscare-installer-dev-only")


def require_install_token(
    x_install_token: Optional[str] = Header(None, alias="X-Install-Token"),
) -> None:
    """Reject install reports without a matching X-Install-Token header.

    The secret is weak by design (embedded in ISOs that ship to customers).
    Its job is to keep internet-wide scanners out of the install_reports
    table, not to prove installer identity.
    """
    if not x_install_token or x_install_token != INSTALL_TOKEN:
        raise HTTPException(status_code=401, detail="invalid install token")


class NetworkInfo(BaseModel):
    iface: Optional[str] = None
    mac: Optional[str] = None
    ip: Optional[str] = None
    gateway: Optional[str] = None
    dns: Optional[List[str]] = None
    mtu: Optional[int] = None
    dhcp_success: Optional[bool] = None
    api_reachable: Optional[bool] = None
    ntp_synced: Optional[bool] = None


class HardwareInfo(BaseModel):
    mac_address: Optional[str] = None
    serial_number: Optional[str] = None
    bios_vendor: Optional[str] = None
    bios_version: Optional[str] = None
    product_name: Optional[str] = None
    cpu_model: Optional[str] = None
    memory_gb: Optional[int] = None
    drive_path: Optional[str] = None
    drive_model: Optional[str] = None
    drive_size_gb: Optional[int] = None
    drive_smart_status: Optional[str] = None
    drive_is_removable: Optional[bool] = None


class InstallReportStart(BaseModel):
    """Phase 1: installer boot + hardware probe complete."""

    installer_id: str = Field(..., description="UUID generated by installer on USB boot")
    installer_version: str
    hardware: HardwareInfo = Field(default_factory=HardwareInfo)
    network: NetworkInfo = Field(default_factory=NetworkInfo)


class InstallReportComplete(BaseModel):
    """Phase 2: install finished (success or failure)."""

    installer_id: str
    success: bool
    error_step: Optional[str] = None
    error_message: Optional[str] = None
    warnings: Optional[List[str]] = None
    image_sha256: Optional[str] = None
    verify_sha256: Optional[str] = None
    duration_s: Optional[int] = None


class InstallReportHalt(BaseModel):
    """Installer halted BEFORE complete — HW-compat gate, disk eligibility, etc.

    Session 208 v38: the HW-compat gate used to `sleep 86400` without ever
    posting anything to Central Command, so an uncertified box showed as
    a silent install_loop. Now every bounded-halt path calls this first.
    """

    installer_id: str
    installer_version: Optional[str] = None
    halt_stage: str = Field(..., description="installer function name, e.g. check_hardware_compat")
    halt_reason: str = Field(..., description="short machine code, e.g. unknown_product")
    hw_product: Optional[str] = None
    bios_vendor: Optional[str] = None
    bios_version: Optional[str] = None
    log_tail: Optional[str] = None


@router.post("/report/start", dependencies=[Depends(require_install_token)])
async def post_install_start(
    report: InstallReportStart,
    db: AsyncSession = Depends(get_db),
) -> Dict[str, Any]:
    """Record install start. Upsert by installer_id so retries don't dup."""
    hw = report.hardware
    net = report.network

    await execute_with_retry(
        db,
        text(
            """
            INSERT INTO install_reports (
                installer_id, mac_address, serial_number, bios_vendor, bios_version,
                product_name, cpu_model, memory_gb,
                drive_path, drive_model, drive_size_gb, drive_smart_status, drive_is_removable,
                network_iface, network_mac, network_ip, network_gateway,
                network_dns, network_mtu, network_dhcp_success,
                network_api_reachable, network_ntp_synced,
                installer_version, install_started_at
            ) VALUES (
                :installer_id, :mac, :serial, :bios_vendor, :bios_version,
                :product, :cpu, :memory,
                :drive_path, :drive_model, :drive_size, :smart, :removable,
                :net_iface, :net_mac, CAST(:net_ip AS INET), CAST(:net_gw AS INET),
                CAST(:net_dns AS TEXT[]), :mtu, :dhcp,
                :api_reach, :ntp,
                :version, NOW()
            )
            ON CONFLICT (installer_id) DO UPDATE SET
                mac_address = EXCLUDED.mac_address,
                bios_version = EXCLUDED.bios_version,
                updated_at = NOW()
            """
        ),
        {
            "installer_id": report.installer_id,
            "mac": hw.mac_address,
            "serial": hw.serial_number,
            "bios_vendor": hw.bios_vendor,
            "bios_version": hw.bios_version,
            "product": hw.product_name,
            "cpu": hw.cpu_model,
            "memory": hw.memory_gb,
            "drive_path": hw.drive_path,
            "drive_model": hw.drive_model,
            "drive_size": hw.drive_size_gb,
            "smart": hw.drive_smart_status,
            "removable": hw.drive_is_removable,
            "net_iface": net.iface,
            "net_mac": net.mac,
            "net_ip": net.ip,
            "net_gw": net.gateway,
            "net_dns": net.dns or [],
            "mtu": net.mtu,
            "dhcp": net.dhcp_success,
            "api_reach": net.api_reachable,
            "ntp": net.ntp_synced,
            "version": report.installer_version,
        },
    )
    await db.commit()

    logger.info(
        "Install start recorded",
        extra={
            "installer_id": report.installer_id,
            "mac": hw.mac_address,
            "product": hw.product_name,
            "drive": hw.drive_model,
        },
    )
    return {"status": "recorded", "installer_id": report.installer_id}


@router.post("/report/complete", dependencies=[Depends(require_install_token)])
async def post_install_complete(
    report: InstallReportComplete,
    db: AsyncSession = Depends(get_db),
) -> Dict[str, Any]:
    """Record install completion (success or failure)."""
    await execute_with_retry(
        db,
        text(
            """
            UPDATE install_reports SET
                install_completed_at = NOW(),
                install_duration_s = :duration,
                install_success = :success,
                error_step = :error_step,
                error_message = :error_msg,
                warnings = CAST(:warnings AS TEXT[]),
                image_sha256 = :image_sha,
                verify_sha256 = :verify_sha,
                updated_at = NOW()
            WHERE installer_id = :installer_id
            """
        ),
        {
            "installer_id": report.installer_id,
            "duration": report.duration_s,
            "success": report.success,
            "error_step": report.error_step,
            "error_msg": report.error_message,
            "warnings": report.warnings or [],
            "image_sha": report.image_sha256,
            "verify_sha": report.verify_sha256,
        },
    )
    await db.commit()

    logger.info(
        "Install complete recorded",
        extra={
            "installer_id": report.installer_id,
            "success": report.success,
            "error_step": report.error_step,
            "duration_s": report.duration_s,
        },
    )
    return {"status": "recorded"}


@router.post("/report/halt", dependencies=[Depends(require_install_token)])
async def post_install_halt(
    report: InstallReportHalt,
    db: AsyncSession = Depends(get_db),
) -> Dict[str, Any]:
    """Record a halt from the installer before it could complete.

    Idempotent — updating is fine, the column set only grows. If the
    installer posted /report/start first we UPDATE; if it halted before
    post_start_report could fire (unusual but possible), we INSERT a
    minimal row keyed by installer_id.
    """
    result = await execute_with_retry(
        db,
        text(
            """
            UPDATE install_reports SET
                halted_at = NOW(),
                halt_stage = :stage,
                halt_reason = :reason,
                halt_log_tail = :log_tail,
                product_name = COALESCE(:hw_product, product_name),
                bios_vendor = COALESCE(:bios_vendor, bios_vendor),
                bios_version = COALESCE(:bios_version, bios_version),
                installer_version = COALESCE(:version, installer_version),
                updated_at = NOW()
            WHERE installer_id = :installer_id
            """
        ),
        {
            "installer_id": report.installer_id,
            "stage": report.halt_stage,
            "reason": report.halt_reason,
            "log_tail": report.log_tail,
            "hw_product": report.hw_product,
            "bios_vendor": report.bios_vendor,
            "bios_version": report.bios_version,
            "version": report.installer_version,
        },
    )
    # If no row was matched, the halt beat the start post — insert the
    # minimum set so the event is never lost.
    if getattr(result, "rowcount", 0) == 0:
        await execute_with_retry(
            db,
            text(
                """
                INSERT INTO install_reports (
                    installer_id, installer_version,
                    product_name, bios_vendor, bios_version,
                    halted_at, halt_stage, halt_reason, halt_log_tail,
                    install_started_at
                ) VALUES (
                    :installer_id, :version,
                    :hw_product, :bios_vendor, :bios_version,
                    NOW(), :stage, :reason, :log_tail,
                    NOW()
                )
                ON CONFLICT (installer_id) DO UPDATE SET
                    halted_at = EXCLUDED.halted_at,
                    halt_stage = EXCLUDED.halt_stage,
                    halt_reason = EXCLUDED.halt_reason,
                    halt_log_tail = EXCLUDED.halt_log_tail,
                    updated_at = NOW()
                """
            ),
            {
                "installer_id": report.installer_id,
                "version": report.installer_version,
                "hw_product": report.hw_product,
                "bios_vendor": report.bios_vendor,
                "bios_version": report.bios_version,
                "stage": report.halt_stage,
                "reason": report.halt_reason,
                "log_tail": report.log_tail,
            },
        )
    await db.commit()

    logger.warning(
        "Install halt recorded",
        extra={
            "installer_id": report.installer_id,
            "halt_stage": report.halt_stage,
            "halt_reason": report.halt_reason,
            "hw_product": report.hw_product,
        },
    )
    return {"status": "recorded"}


# --- Admin UI — list recent install reports ----------------------------------

@router.get("/report", dependencies=[Depends(require_auth)])
async def list_install_reports(
    limit: int = 50,
    only_failures: bool = False,
    db: AsyncSession = Depends(get_db),
) -> Dict[str, Any]:
    """List recent install reports for the admin dashboard."""
    limit = max(1, min(200, int(limit)))

    query = """
        SELECT installer_id, mac_address, serial_number, product_name,
               drive_model, drive_size_gb, drive_smart_status,
               network_api_reachable, network_ntp_synced,
               install_started_at, install_completed_at, install_duration_s,
               install_success, error_step, error_message, warnings,
               installer_version, image_sha256, verify_sha256
        FROM install_reports
    """
    if only_failures:
        query += " WHERE install_success = false"
    query += " ORDER BY install_started_at DESC LIMIT :lim"

    result = await execute_with_retry(db, text(query), {"lim": limit})
    rows = [dict(r._mapping) for r in result.fetchall()]

    # Convert datetimes + UUIDs for JSON
    for r in rows:
        for k, v in list(r.items()):
            if isinstance(v, datetime):
                r[k] = v.isoformat()
            elif hasattr(v, "hex"):  # UUID
                r[k] = str(v)

    # Summary counts
    summary_result = await execute_with_retry(
        db,
        text(
            """
            SELECT
                COUNT(*) FILTER (WHERE install_success = true) as success_count,
                COUNT(*) FILTER (WHERE install_success = false) as failure_count,
                COUNT(*) FILTER (WHERE install_completed_at IS NULL) as in_progress_count,
                COUNT(*) FILTER (WHERE install_started_at > NOW() - INTERVAL '7 days') as total_7d
            FROM install_reports
            """
        ),
    )
    summary = dict(summary_result.fetchone()._mapping)

    return {
        "reports": rows,
        "summary": summary,
        "computed_at": datetime.now(timezone.utc).isoformat(),
    }
