# Runbook: SSL/TLS Certificate Expiry Remediation
#
# Handles expiring or expired SSL/TLS certificates by checking expiry,
# renewing via Let's Encrypt/ACME, and reloading services.
#
# HIPAA Controls: ยง164.312(e)(1)

id: RB-CERT-001
name: Certificate Expiry Remediation
version: "1.0"
description: Automated SSL/TLS certificate renewal

triggers:
  - event_type: cert_expiry_warning
  - event_type: cert_expired

severity:
  - high
  - medium

applicable_to:
  - linux_server
  - network_device

hipaa_controls:
  - "164.312(e)(1)"  # Transmission Security

sla_target_seconds: 3600  # 1 hour

steps:
  - step: 1
    name: check_certificate_expiry
    description: Check certificate expiration dates
    script: scripts/check_cert_expiry.sh
    timeout_seconds: 30
    retry_on_failure: false
    evidence_required:
      - cert_subject
      - cert_expiry_date
      - days_until_expiry

  - step: 2
    name: backup_current_cert
    description: Backup existing certificate before renewal
    script: scripts/backup_cert.sh
    timeout_seconds: 10
    retry_on_failure: false
    evidence_required:
      - backup_path
      - backup_checksum

  - step: 3
    name: renew_certificate
    description: Renew certificate via ACME (Let's Encrypt)
    script: scripts/renew_cert_acme.sh
    timeout_seconds: 120
    retry_on_failure: true
    retry_count: 3
    evidence_required:
      - renewal_method
      - new_cert_expiry_date
      - acme_response

  - step: 4
    name: reload_services
    description: Reload services using certificate (nginx, apache, etc)
    script: scripts/reload_web_services.sh
    timeout_seconds: 60
    retry_on_failure: true
    retry_count: 2
    evidence_required:
      - services_reloaded
      - service_status

rollback:
  - action: restore_certificate
    script: scripts/restore_cert_backup.sh
  - action: alert_administrator
    message: "Certificate renewal failed - restored backup"

evidence_artifacts:
  required:
    - outputs.cert_subject
    - outputs.old_expiry_date
    - outputs.new_expiry_date
    - outputs.days_until_expiry
    - checksums.certificate_file
  optional:
    - log_excerpts.acme_log

success_criteria:
  - days_until_expiry > 30
  - service_status == "active"

post_execution_validation:
  - name: verify_cert_valid
    command: "openssl x509 -in /etc/ssl/certs/domain.crt -noout -checkend 2592000"
    expected_exit_code: 0  # Valid for at least 30 days
  - name: verify_web_service
    command: "curl -s -o /dev/null -w '%{http_code}' https://localhost/"
    expected_output: "200"

metadata:
  author: MSP Compliance Platform
  created: 2025-11-01
  last_modified: 2025-11-01
  tested: true
  production_ready: true
