package healing

// builtinRules returns all built-in L1 deterministic rules.
// These are direct ports of the Python rules in level1_deterministic.py.
func builtinRules() []*Rule {
	return []*Rule{
		// --- NixOS/Generic Rules ---

		{
			ID:          "L1-PATCH-001",
			Name:        "Patching Generation Drift",
			Description: "NixOS generation behind baseline, trigger update",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "patching"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "details.generation_drift", Operator: OpEquals, Value: true},
			},
			Action:          "update_to_baseline_generation",
			ActionParams:    map[string]interface{}{"verify_after": true},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(B)"},
			Enabled:         true,
			Priority:        10,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-AV-001",
			Name:        "AV/EDR Service Down",
			Description: "Antivirus or EDR service not running",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "av_edr"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "details.service_running", Operator: OpEquals, Value: false},
			},
			Action:          "restart_av_service",
			ActionParams:    map[string]interface{}{"service_name": "clamav-daemon"},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(B)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-BACKUP-001",
			Name:        "Backup Job Failure",
			Description: "Backup job failed or missing",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "backup"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "details.last_backup_success", Operator: OpEquals, Value: false},
			},
			Action:          "run_backup_job",
			ActionParams:    map[string]interface{}{"job_name": "restic-backup"},
			HIPAAControls:   []string{"164.308(a)(7)(ii)(A)"},
			Enabled:         true,
			Priority:        15,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-BACKUP-002",
			Name:        "Backup Age Exceeded",
			Description: "Last successful backup too old",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "backup"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "details.age_hours", Operator: OpGreaterThan, Value: float64(24)},
			},
			Action:          "run_backup_job",
			ActionParams:    map[string]interface{}{"job_name": "restic-backup", "force": true},
			HIPAAControls:   []string{"164.308(a)(7)(ii)(A)"},
			Enabled:         true,
			Priority:        20,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LOG-001",
			Name:        "Logging Service Down",
			Description: "Audit logging service not running",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "logging"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "details.services_running", Operator: OpEquals, Value: false},
			},
			Action:          "restart_logging_services",
			ActionParams:    map[string]interface{}{},
			HIPAAControls:   []string{"164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-FW-001",
			Name:        "Firewall Configuration Drift",
			Description: "Firewall rules deviated from baseline",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "firewall"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "platform", Operator: OpNotEquals, Value: "nixos"},
			},
			Action:          "restore_firewall_baseline",
			ActionParams:    map[string]interface{}{},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        10,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-FW-002",
			Name:        "Windows Firewall Disabled",
			Description: "Windows Firewall profile disabled — re-enable via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "firewall_status"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-AUDIT-002",
			Name:        "Windows Audit Policy Drift",
			Description: "Audit policy changed from compliant baseline — restore",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "audit_policy"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-002", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-ENCRYPT-001",
			Name:        "Encryption Status Alert",
			Description: "Encryption issue detected - escalate to human",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "encryption"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action: "escalate",
			ActionParams: map[string]interface{}{
				"reason":  "Encryption changes require human verification",
				"urgency": "high",
			},
			HIPAAControls:   []string{"164.312(a)(2)(iv)"},
			Enabled:         true,
			Priority:        1,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-CERT-001",
			Name:        "Certificate Expiring",
			Description: "TLS certificate expiring within 30 days",
			Conditions: []RuleCondition{
				{Field: "incident_type", Operator: OpEquals, Value: "cert_expiry"},
				{Field: "details.days_remaining", Operator: OpLessThan, Value: float64(30)},
			},
			Action:          "renew_certificate",
			ActionParams:    map[string]interface{}{},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        25,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-DISK-001",
			Name:        "Disk Space Critical",
			Description: "Disk usage above 90%",
			Conditions: []RuleCondition{
				{Field: "incident_type", Operator: OpEquals, Value: "disk_space"},
				{Field: "details.usage_percent", Operator: OpGreaterThan, Value: float64(90)},
			},
			Action:          "cleanup_disk_space",
			ActionParams:    map[string]interface{}{"targets": []interface{}{"/var/log", "/tmp", "/var/cache"}},
			HIPAAControls:   []string{},
			Enabled:         true,
			Priority:        15,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-SERVICE-001",
			Name:        "Service Crash Loop",
			Description: "Service restarting repeatedly",
			Conditions: []RuleCondition{
				{Field: "incident_type", Operator: OpEquals, Value: "service_crash"},
				{Field: "details.restart_count", Operator: OpGreaterThan, Value: float64(3)},
			},
			Action: "escalate",
			ActionParams: map[string]interface{}{
				"reason":       "Service in crash loop - requires investigation",
				"include_logs": true,
			},
			HIPAAControls:   []string{},
			Enabled:         true,
			Priority:        10,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},

		// --- Linux L1 Rules ---

		{
			ID:          "L1-SSH-001",
			Name:        "SSH Configuration Drift",
			Description: "SSH configuration non-compliant — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "ssh_config"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(d)", "164.312(a)(1)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-KERN-001",
			Name:        "Kernel Parameter Drift",
			Description: "Unsafe kernel parameters detected — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "kernel"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-KERN-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-CRON-001",
			Name:        "Cron Permission Drift",
			Description: "Cron files have insecure permissions — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "cron"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-CRON-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(1)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-SUID-001",
			Name:        "Unauthorized SUID Binary",
			Description: "SUID binaries found in /tmp — remove immediately",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "permissions"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "distro", Operator: OpNotEquals, Value: nil},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-SUID-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(1)", "164.308(a)(5)(ii)(C)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-FW-001",
			Name:        "Linux Firewall Drift",
			Description: "Linux firewall disabled or flushed — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "firewall"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "distro", Operator: OpNotEquals, Value: nil},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-FW-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-AUDIT-001",
			Name:        "Linux Audit Daemon Drift",
			Description: "auditd not running on Linux — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "audit"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-AUDIT-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-SVC-001",
			Name:        "Linux Service Drift",
			Description: "Required Linux service not running — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "services"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "distro", Operator: OpNotEquals, Value: nil},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(1)", "164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-LOG-001",
			Name:        "Linux Logging Drift",
			Description: "rsyslog not running on Linux — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "logging"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-LOG-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-PERM-001",
			Name:        "Linux Permissions Drift",
			Description: "Insecure file permissions on Linux — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "permissions"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
				{Field: "distro", Operator: OpNotEquals, Value: nil},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(1)", "164.312(c)(1)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-NET-001",
			Name:        "Linux Network Hardening Drift",
			Description: "Network sysctl params non-compliant — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "network"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-NET-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-BANNER-001",
			Name:        "Linux Login Banner Drift",
			Description: "HIPAA authorized-use banner missing — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "banner"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-BANNER-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(d)"},
			Enabled:         true,
			Priority:        15,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-CRYPTO-001",
			Name:        "Linux Cryptographic Policy Drift",
			Description: "Weak SSH ciphers/MACs/KEX detected — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "crypto"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-CRYPTO-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)", "164.312(e)(2)(ii)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-LIN-IR-001",
			Name:        "Linux Incident Response Readiness Drift",
			Description: "IR tools/logging not configured — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "incident_response"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_linux_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "LIN-IR-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(b)", "164.308(a)(6)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},

		// --- Windows L1 Rules ---

		{
			ID:          "L1-WIN-SVC-DNS",
			Name:        "Windows DNS Service Down",
			Description: "DNS service not running — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "service_dns"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SVC-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-SEC-SMB",
			Name:        "Windows SMB Signing Drift",
			Description: "SMB signing not required — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "smb_signing"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-007", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)", "164.312(e)(2)(i)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-SVC-WUAUSERV",
			Name:        "Windows Update Service Down",
			Description: "Windows Update service not running — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "service_wuauserv"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SVC-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(B)"},
			Enabled:         true,
			Priority:        10,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-WIN-NET-PROFILE",
			Name:        "Windows Network Profile Drift",
			Description: "Network profile set to Public — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "network_profile"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-NET-003", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-WIN-SEC-SCREENLOCK",
			Name:        "Windows Screen Lock Drift",
			Description: "Screen lock timeout missing or too long — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "screen_lock_policy"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-016", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(2)(iii)"},
			Enabled:         true,
			Priority:        8,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-WIN-SEC-BITLOCKER",
			Name:        "Windows BitLocker Disabled",
			Description: "BitLocker drive encryption off — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "bitlocker_status"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-005", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(a)(2)(iv)", "164.312(e)(2)(ii)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-SVC-NETLOGON",
			Name:        "Windows NetLogon Service Down",
			Description: "NetLogon service not running — restore domain authentication",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "service_netlogon"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SVC-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(d)", "164.312(a)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-DNS-HIJACK",
			Name:        "Windows DNS Configuration Drift",
			Description: "DNS servers changed to unauthorized addresses — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "dns_config"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-NET-001", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-SEC-DEFENDER-EXCL",
			Name:        "Windows Defender Exclusion Drift",
			Description: "Suspicious Defender exclusions detected — remediate via runbook",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "defender_exclusions"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-017", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(B)", "164.312(b)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
			GPOManaged:      true,
		},
		{
			ID:          "L1-PERSIST-TASK-001",
			Name:        "Scheduled Task Persistence Detected",
			Description: "Suspicious scheduled tasks in root namespace — remove",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "scheduled_task_persistence"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-018", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(C)", "164.312(a)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-PERSIST-REG-001",
			Name:        "Registry Run Key Persistence Detected",
			Description: "Suspicious registry Run key entries — remove",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "registry_run_persistence"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-019", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(C)", "164.312(a)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-WIN-SEC-SMB1",
			Name:        "SMBv1 Protocol Enabled",
			Description: "SMBv1 protocol enabled — disable to prevent EternalBlue-class attacks",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "smb1_protocol"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-020", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.312(e)(1)", "164.312(e)(2)(i)"},
			Enabled:         true,
			Priority:        5,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
		{
			ID:          "L1-PERSIST-WMI-001",
			Name:        "WMI Event Subscription Persistence Detected",
			Description: "Suspicious WMI event subscriptions — remove persistence mechanism",
			Conditions: []RuleCondition{
				{Field: "check_type", Operator: OpEquals, Value: "wmi_event_persistence"},
				{Field: "drift_detected", Operator: OpEquals, Value: true},
			},
			Action:          "run_windows_runbook",
			ActionParams:    map[string]interface{}{"runbook_id": "RB-WIN-SEC-021", "phases": []interface{}{"remediate", "verify"}},
			HIPAAControls:   []string{"164.308(a)(5)(ii)(C)", "164.312(a)(1)"},
			Enabled:         true,
			Priority:        3,
			CooldownSeconds: 300,
			MaxRetries:      1,
			Source:          "builtin",
		},
	}
}
