// OsirisCare Compliance Agent gRPC Service
//
// This defines the communication protocol between Go Agents on Windows
// workstations and the Python Compliance Agent on the NixOS appliance.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CapabilityTier defines what actions the agent can take
type CapabilityTier int32

const (
	CapabilityTier_MONITOR_ONLY     CapabilityTier = 0 // Can only report drift
	CapabilityTier_SELF_HEAL        CapabilityTier = 1 // Can attempt automated remediation
	CapabilityTier_FULL_REMEDIATION CapabilityTier = 2 // Can perform all remediations
)

// Enum value maps for CapabilityTier.
var (
	CapabilityTier_name = map[int32]string{
		0: "MONITOR_ONLY",
		1: "SELF_HEAL",
		2: "FULL_REMEDIATION",
	}
	CapabilityTier_value = map[string]int32{
		"MONITOR_ONLY":     0,
		"SELF_HEAL":        1,
		"FULL_REMEDIATION": 2,
	}
)

func (x CapabilityTier) Enum() *CapabilityTier {
	p := new(CapabilityTier)
	*p = x
	return p
}

func (x CapabilityTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_compliance_proto_enumTypes[0].Descriptor()
}

func (CapabilityTier) Type() protoreflect.EnumType {
	return &file_proto_compliance_proto_enumTypes[0]
}

func (x CapabilityTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityTier.Descriptor instead.
func (CapabilityTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is sent when an agent first connects
type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hostname          string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsVersion         string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	InstalledSoftware []string               `protobuf:"bytes,4,rep,name=installed_software,json=installedSoftware,proto3" json:"installed_software,omitempty"`
	MacAddress        string                 `protobuf:"bytes,5,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	NeedsCertificates bool                   `protobuf:"varint,6,opt,name=needs_certificates,json=needsCertificates,proto3" json:"needs_certificates,omitempty"` // True on first connect when agent has no certs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetInstalledSoftware() []string {
	if x != nil {
		return x.InstalledSoftware
	}
	return nil
}

func (x *RegisterRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *RegisterRequest) GetNeedsCertificates() bool {
	if x != nil {
		return x.NeedsCertificates
	}
	return false
}

// RegisterResponse provides agent configuration
type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,2,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"`
	EnabledChecks        []string               `protobuf:"bytes,3,rep,name=enabled_checks,json=enabledChecks,proto3" json:"enabled_checks,omitempty"`
	CapabilityTier       CapabilityTier         `protobuf:"varint,4,opt,name=capability_tier,json=capabilityTier,proto3,enum=compliance.CapabilityTier" json:"capability_tier,omitempty"`
	CheckConfig          map[string]string      `protobuf:"bytes,5,rep,name=check_config,json=checkConfig,proto3" json:"check_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CaCertPem            []byte                 `protobuf:"bytes,6,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`          // CA certificate for TLS verification
	AgentCertPem         []byte                 `protobuf:"bytes,7,opt,name=agent_cert_pem,json=agentCertPem,proto3" json:"agent_cert_pem,omitempty"` // Signed client certificate for this agent
	AgentKeyPem          []byte                 `protobuf:"bytes,8,opt,name=agent_key_pem,json=agentKeyPem,proto3" json:"agent_key_pem,omitempty"`    // Private key for the client certificate
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetEnabledChecks() []string {
	if x != nil {
		return x.EnabledChecks
	}
	return nil
}

func (x *RegisterResponse) GetCapabilityTier() CapabilityTier {
	if x != nil {
		return x.CapabilityTier
	}
	return CapabilityTier_MONITOR_ONLY
}

func (x *RegisterResponse) GetCheckConfig() map[string]string {
	if x != nil {
		return x.CheckConfig
	}
	return nil
}

func (x *RegisterResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *RegisterResponse) GetAgentCertPem() []byte {
	if x != nil {
		return x.AgentCertPem
	}
	return nil
}

func (x *RegisterResponse) GetAgentKeyPem() []byte {
	if x != nil {
		return x.AgentKeyPem
	}
	return nil
}

// DriftEvent represents a compliance check result
type DriftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CheckType     string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // bitlocker, defender, firewall, patches, screenlock, rmm
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	Expected      string                 `protobuf:"bytes,5,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual        string                 `protobuf:"bytes,6,opt,name=actual,proto3" json:"actual,omitempty"`
	HipaaControl  string                 `protobuf:"bytes,7,opt,name=hipaa_control,json=hipaaControl,proto3" json:"hipaa_control,omitempty"` // e.g., "164.312(a)(2)(iv)"
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix timestamp
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftEvent) Reset() {
	*x = DriftEvent{}
	mi := &file_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftEvent) ProtoMessage() {}

func (x *DriftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftEvent.ProtoReflect.Descriptor instead.
func (*DriftEvent) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *DriftEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DriftEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DriftEvent) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *DriftEvent) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *DriftEvent) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *DriftEvent) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

func (x *DriftEvent) GetHipaaControl() string {
	if x != nil {
		return x.HipaaControl
	}
	return ""
}

func (x *DriftEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DriftEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DriftAck acknowledges receipt of a drift event
// Can optionally include a heal command for the agent to execute immediately
type DriftAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EventId  string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Received bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	Error    string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Optional heal command - if set, agent should execute this heal
	HealCommand   *HealCommand `protobuf:"bytes,4,opt,name=heal_command,json=healCommand,proto3" json:"heal_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftAck) Reset() {
	*x = DriftAck{}
	mi := &file_proto_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftAck) ProtoMessage() {}

func (x *DriftAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftAck.ProtoReflect.Descriptor instead.
func (*DriftAck) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *DriftAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DriftAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *DriftAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DriftAck) GetHealCommand() *HealCommand {
	if x != nil {
		return x.HealCommand
	}
	return nil
}

// HealCommand tells Go agent to execute a specific remediation
type HealCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                    // Unique ID for tracking
	CheckType      string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`                                                    // firewall, defender, bitlocker, screenlock, patches
	Action         string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                                                           // enable, start, configure, etc.
	Params         map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Action-specific parameters
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                    // Max execution time (default 60)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealCommand) Reset() {
	*x = HealCommand{}
	mi := &file_proto_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealCommand) ProtoMessage() {}

func (x *HealCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealCommand.ProtoReflect.Descriptor instead.
func (*HealCommand) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *HealCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *HealCommand) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HealCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *HealCommand) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// HealingResult reports the outcome of self-healing or commanded healing
type HealingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CheckType     string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Artifacts     map[string]string      `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., bitlocker recovery key
	CommandId     string                 `protobuf:"bytes,8,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                          // If responding to HealCommand, include its ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingResult) Reset() {
	*x = HealingResult{}
	mi := &file_proto_compliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingResult) ProtoMessage() {}

func (x *HealingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingResult.ProtoReflect.Descriptor instead.
func (*HealingResult) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *HealingResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HealingResult) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HealingResult) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealingResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HealingResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealingResult) GetArtifacts() map[string]string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *HealingResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// HealingAck acknowledges healing result
type HealingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Received      bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingAck) Reset() {
	*x = HealingAck{}
	mi := &file_proto_compliance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingAck) ProtoMessage() {}

func (x *HealingAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingAck.ProtoReflect.Descriptor instead.
func (*HealingAck) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{6}
}

func (x *HealingAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *HealingAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

// HeartbeatRequest is sent periodically to indicate liveness
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DriftCount    int32                  `protobuf:"varint,3,opt,name=drift_count,json=driftCount,proto3" json:"drift_count,omitempty"`       // Number of drift events since last heartbeat
	HealingCount  int32                  `protobuf:"varint,4,opt,name=healing_count,json=healingCount,proto3" json:"healing_count,omitempty"` // Number of healing attempts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_compliance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetDriftCount() int32 {
	if x != nil {
		return x.DriftCount
	}
	return 0
}

func (x *HeartbeatRequest) GetHealingCount() int32 {
	if x != nil {
		return x.HealingCount
	}
	return 0
}

// HeartbeatResponse can signal config changes and pending commands
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ConfigChanged   bool                   `protobuf:"varint,2,opt,name=config_changed,json=configChanged,proto3" json:"config_changed,omitempty"`      // If true, agent should re-register
	PendingCommands []*HealCommand         `protobuf:"bytes,3,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"` // Commands queued for this agent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_compliance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetConfigChanged() bool {
	if x != nil {
		return x.ConfigChanged
	}
	return false
}

func (x *HeartbeatResponse) GetPendingCommands() []*HealCommand {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

// RMMStatusReport reports detected RMM tools
type RMMStatusReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DetectedAgents []*RMMAgent            `protobuf:"bytes,3,rep,name=detected_agents,json=detectedAgents,proto3" json:"detected_agents,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RMMStatusReport) Reset() {
	*x = RMMStatusReport{}
	mi := &file_proto_compliance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RMMStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMMStatusReport) ProtoMessage() {}

func (x *RMMStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMMStatusReport.ProtoReflect.Descriptor instead.
func (*RMMStatusReport) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{9}
}

func (x *RMMStatusReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RMMStatusReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RMMStatusReport) GetDetectedAgents() []*RMMAgent {
	if x != nil {
		return x.DetectedAgents
	}
	return nil
}

func (x *RMMStatusReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// RMMAgent represents a detected RMM tool
type RMMAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g., "ConnectWise", "Datto", "NinjaRMM"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RMMAgent) Reset() {
	*x = RMMAgent{}
	mi := &file_proto_compliance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RMMAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMMAgent) ProtoMessage() {}

func (x *RMMAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMMAgent.ProtoReflect.Descriptor instead.
func (*RMMAgent) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{10}
}

func (x *RMMAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RMMAgent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RMMAgent) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *RMMAgent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// RMMAck acknowledges RMM status report
type RMMAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RMMAck) Reset() {
	*x = RMMAck{}
	mi := &file_proto_compliance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RMMAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMMAck) ProtoMessage() {}

func (x *RMMAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMMAck.ProtoReflect.Descriptor instead.
func (*RMMAck) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{11}
}

func (x *RMMAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_proto_compliance_proto protoreflect.FileDescriptor

const file_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/compliance.proto\x12\n" +
	"compliance\"\xf0\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12-\n" +
	"\x12installed_software\x18\x04 \x03(\tR\x11installedSoftware\x12\x1f\n" +
	"\vmac_address\x18\x05 \x01(\tR\n" +
	"macAddress\x12-\n" +
	"\x12needs_certificates\x18\x06 \x01(\bR\x11needsCertificates\"\xcb\x03\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\x16check_interval_seconds\x18\x02 \x01(\x05R\x14checkIntervalSeconds\x12%\n" +
	"\x0eenabled_checks\x18\x03 \x03(\tR\renabledChecks\x12C\n" +
	"\x0fcapability_tier\x18\x04 \x01(\x0e2\x1a.compliance.CapabilityTierR\x0ecapabilityTier\x12P\n" +
	"\fcheck_config\x18\x05 \x03(\v2-.compliance.RegisterResponse.CheckConfigEntryR\vcheckConfig\x12\x1e\n" +
	"\vca_cert_pem\x18\x06 \x01(\fR\tcaCertPem\x12$\n" +
	"\x0eagent_cert_pem\x18\a \x01(\fR\fagentCertPem\x12\"\n" +
	"\ragent_key_pem\x18\b \x01(\fR\vagentKeyPem\x1a>\n" +
	"\x10CheckConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x02\n" +
	"\n" +
	"DriftEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x1a\n" +
	"\bexpected\x18\x05 \x01(\tR\bexpected\x12\x16\n" +
	"\x06actual\x18\x06 \x01(\tR\x06actual\x12#\n" +
	"\rhipaa_control\x18\a \x01(\tR\fhipaaControl\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.compliance.DriftEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\bDriftAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12:\n" +
	"\fheal_command\x18\x04 \x01(\v2\x17.compliance.HealCommandR\vhealCommand\"\x84\x02\n" +
	"\vHealCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12;\n" +
	"\x06params\x18\x04 \x03(\v2#.compliance.HealCommand.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x02\n" +
	"\rHealingResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12F\n" +
	"\tartifacts\x18\a \x03(\v2(.compliance.HealingResult.ArtifactsEntryR\tartifacts\x12\x1d\n" +
	"\n" +
	"command_id\x18\b \x01(\tR\tcommandId\x1a<\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\n" +
	"HealingAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\"\x91\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vdrift_count\x18\x03 \x01(\x05R\n" +
	"driftCount\x12#\n" +
	"\rhealing_count\x18\x04 \x01(\x05R\fhealingCount\"\xa2\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12%\n" +
	"\x0econfig_changed\x18\x02 \x01(\bR\rconfigChanged\x12B\n" +
	"\x10pending_commands\x18\x03 \x03(\v2\x17.compliance.HealCommandR\x0fpendingCommands\"\xa5\x01\n" +
	"\x0fRMMStatusReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12=\n" +
	"\x0fdetected_agents\x18\x03 \x03(\v2\x14.compliance.RMMAgentR\x0edetectedAgents\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"u\n" +
	"\bRMMAgent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\"$\n" +
	"\x06RMMAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived*G\n" +
	"\x0eCapabilityTier\x12\x10\n" +
	"\fMONITOR_ONLY\x10\x00\x12\r\n" +
	"\tSELF_HEAL\x10\x01\x12\x14\n" +
	"\x10FULL_REMEDIATION\x10\x022\xeb\x02\n" +
	"\x0fComplianceAgent\x12E\n" +
	"\bRegister\x12\x1b.compliance.RegisterRequest\x1a\x1c.compliance.RegisterResponse\x12?\n" +
	"\vReportDrift\x12\x16.compliance.DriftEvent\x1a\x14.compliance.DriftAck(\x010\x01\x12B\n" +
	"\rReportHealing\x12\x19.compliance.HealingResult\x1a\x16.compliance.HealingAck\x12H\n" +
	"\tHeartbeat\x12\x1c.compliance.HeartbeatRequest\x1a\x1d.compliance.HeartbeatResponse\x12B\n" +
	"\x0fReportRMMStatus\x12\x1b.compliance.RMMStatusReport\x1a\x12.compliance.RMMAckB#Z!github.com/osiriscare/agent/protob\x06proto3"

var (
	file_proto_compliance_proto_rawDescOnce sync.Once
	file_proto_compliance_proto_rawDescData []byte
)

func file_proto_compliance_proto_rawDescGZIP() []byte {
	file_proto_compliance_proto_rawDescOnce.Do(func() {
		file_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)))
	})
	return file_proto_compliance_proto_rawDescData
}

var file_proto_compliance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_compliance_proto_goTypes = []any{
	(CapabilityTier)(0),       // 0: compliance.CapabilityTier
	(*RegisterRequest)(nil),   // 1: compliance.RegisterRequest
	(*RegisterResponse)(nil),  // 2: compliance.RegisterResponse
	(*DriftEvent)(nil),        // 3: compliance.DriftEvent
	(*DriftAck)(nil),          // 4: compliance.DriftAck
	(*HealCommand)(nil),       // 5: compliance.HealCommand
	(*HealingResult)(nil),     // 6: compliance.HealingResult
	(*HealingAck)(nil),        // 7: compliance.HealingAck
	(*HeartbeatRequest)(nil),  // 8: compliance.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 9: compliance.HeartbeatResponse
	(*RMMStatusReport)(nil),   // 10: compliance.RMMStatusReport
	(*RMMAgent)(nil),          // 11: compliance.RMMAgent
	(*RMMAck)(nil),            // 12: compliance.RMMAck
	nil,                       // 13: compliance.RegisterResponse.CheckConfigEntry
	nil,                       // 14: compliance.DriftEvent.MetadataEntry
	nil,                       // 15: compliance.HealCommand.ParamsEntry
	nil,                       // 16: compliance.HealingResult.ArtifactsEntry
}
var file_proto_compliance_proto_depIdxs = []int32{
	0,  // 0: compliance.RegisterResponse.capability_tier:type_name -> compliance.CapabilityTier
	13, // 1: compliance.RegisterResponse.check_config:type_name -> compliance.RegisterResponse.CheckConfigEntry
	14, // 2: compliance.DriftEvent.metadata:type_name -> compliance.DriftEvent.MetadataEntry
	5,  // 3: compliance.DriftAck.heal_command:type_name -> compliance.HealCommand
	15, // 4: compliance.HealCommand.params:type_name -> compliance.HealCommand.ParamsEntry
	16, // 5: compliance.HealingResult.artifacts:type_name -> compliance.HealingResult.ArtifactsEntry
	5,  // 6: compliance.HeartbeatResponse.pending_commands:type_name -> compliance.HealCommand
	11, // 7: compliance.RMMStatusReport.detected_agents:type_name -> compliance.RMMAgent
	1,  // 8: compliance.ComplianceAgent.Register:input_type -> compliance.RegisterRequest
	3,  // 9: compliance.ComplianceAgent.ReportDrift:input_type -> compliance.DriftEvent
	6,  // 10: compliance.ComplianceAgent.ReportHealing:input_type -> compliance.HealingResult
	8,  // 11: compliance.ComplianceAgent.Heartbeat:input_type -> compliance.HeartbeatRequest
	10, // 12: compliance.ComplianceAgent.ReportRMMStatus:input_type -> compliance.RMMStatusReport
	2,  // 13: compliance.ComplianceAgent.Register:output_type -> compliance.RegisterResponse
	4,  // 14: compliance.ComplianceAgent.ReportDrift:output_type -> compliance.DriftAck
	7,  // 15: compliance.ComplianceAgent.ReportHealing:output_type -> compliance.HealingAck
	9,  // 16: compliance.ComplianceAgent.Heartbeat:output_type -> compliance.HeartbeatResponse
	12, // 17: compliance.ComplianceAgent.ReportRMMStatus:output_type -> compliance.RMMAck
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_compliance_proto_init() }
func file_proto_compliance_proto_init() {
	if File_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compliance_proto_goTypes,
		DependencyIndexes: file_proto_compliance_proto_depIdxs,
		EnumInfos:         file_proto_compliance_proto_enumTypes,
		MessageInfos:      file_proto_compliance_proto_msgTypes,
	}.Build()
	File_proto_compliance_proto = out.File
	file_proto_compliance_proto_goTypes = nil
	file_proto_compliance_proto_depIdxs = nil
}
