"""P0-D2 drift guard (Task #77 Phase B-lite + #87, 2026-05-14).

The three `tests/fixtures/schema/` sidecars — `prod_columns.json`
(names), `prod_column_types.json` (types), `prod_column_widths.json`
(varchar/char widths) — are regenerated by ONE prod query (documented
in `test_sql_columns_match_schema.py`). names and types MUST stay
key-set identical (same tables, same per-table column sets); widths is
a SUBSET (only length-constrained columns) and MUST stay ⊆ names.

This meta-test fails loudly if the three ever diverge — the failure
mode the sidecar split was designed to make impossible. If you
hand-edit one fixture (mode (b) forward-merge of a local migration),
you must edit all three in lockstep or this gate stops you.

Why a sidecar instead of augmenting `prod_columns.json` in place: the
repo already keeps per-column schema facets in their own files
(`prod_column_widths.json`, `prod_unique_indexes.json`). The typed
fixture follows that established convention. See
`audit/coach-77-phase-b-lite-approach-delta-gate-a-2026-05-14.md`.
"""
from __future__ import annotations

import json
import pathlib

_SCHEMA_DIR = (
    pathlib.Path(__file__).resolve().parent / "fixtures" / "schema"
)
_NAMES = _SCHEMA_DIR / "prod_columns.json"
_TYPES = _SCHEMA_DIR / "prod_column_types.json"
_WIDTHS = _SCHEMA_DIR / "prod_column_widths.json"


def _load(path: pathlib.Path):
    return json.loads(path.read_text())


def test_all_fixtures_exist():
    assert _NAMES.is_file(), f"missing {_NAMES}"
    assert _TYPES.is_file(), f"missing {_TYPES}"
    assert _WIDTHS.is_file(), f"missing {_WIDTHS}"


def test_table_sets_identical():
    names = _load(_NAMES)
    types = _load(_TYPES)
    only_names = sorted(set(names) - set(types))
    only_types = sorted(set(types) - set(names))
    assert not only_names and not only_types, (
        "prod_columns.json and prod_column_types.json have diverged "
        "(table sets differ). Regenerate BOTH with the combined command "
        "in test_sql_columns_match_schema.py.\n"
        f"  only in prod_columns.json: {only_names}\n"
        f"  only in prod_column_types.json: {only_types}"
    )


def test_per_table_column_sets_identical():
    names = _load(_NAMES)
    types = _load(_TYPES)
    mismatches: list[str] = []
    for table in sorted(set(names) & set(types)):
        ncols = set(names[table])
        tcols = set(types[table])
        if ncols != tcols:
            mismatches.append(
                f"  {table}: only-in-names={sorted(ncols - tcols)} "
                f"only-in-types={sorted(tcols - ncols)}"
            )
    assert not mismatches, (
        "prod_columns.json and prod_column_types.json have diverged "
        "(per-table column sets differ). Regenerate BOTH with the "
        "combined command in test_sql_columns_match_schema.py.\n"
        + "\n".join(mismatches)
    )


def test_widths_fixture_is_subset_of_columns():
    """`prod_column_widths.json` (Task #87) only covers columns that
    have a `character_maximum_length` (varchar/char), so it is NOT
    key-set identical to the other two — it is a SUBSET. Every table
    and every (table, column) it lists must still exist in
    `prod_columns.json`. The reverse direction is NOT checked: most
    columns have no width and are correctly absent from widths.

    All three sidecars are regenerated by the one combined command in
    test_sql_columns_match_schema.py, so a divergence here means a
    stale or hand-edited fixture.
    """
    names = _load(_NAMES)
    widths = _load(_WIDTHS)
    extra_tables = sorted(set(widths) - set(names))
    assert not extra_tables, (
        "prod_column_widths.json lists tables absent from "
        "prod_columns.json — regenerate all three with the combined "
        f"command. Orphan tables: {extra_tables}"
    )
    orphan_cols: list[str] = []
    for table, cols in widths.items():
        known = set(names.get(table, []))
        for col in cols:
            if col not in known:
                orphan_cols.append(f"  {table}.{col}")
    assert not orphan_cols, (
        "prod_column_widths.json lists (table, column) pairs absent "
        "from prod_columns.json — regenerate all three with the "
        "combined command:\n" + "\n".join(orphan_cols)
    )


def test_typed_fixture_values_are_nonempty_strings():
    """Every column maps to a non-empty data_type string — guards
    against a malformed regen (e.g. NULLs serialized as empty)."""
    types = _load(_TYPES)
    bad: list[str] = []
    for table, cols in types.items():
        for col, dtype in cols.items():
            if not isinstance(dtype, str) or not dtype:
                bad.append(f"  {table}.{col} = {dtype!r}")
    assert not bad, (
        "prod_column_types.json has columns with missing/empty "
        "data_type values:\n" + "\n".join(bad)
    )
