"""P0-D2 drift guard (Task #77 Phase B-lite, 2026-05-14).

`tests/fixtures/schema/prod_columns.json` (names) and its typed sidecar
`prod_column_types.json` are regenerated by ONE command (documented in
`test_sql_columns_match_schema.py` — the names fixture is DERIVED from
the typed pull). They MUST stay key-set identical: same tables, same
per-table column sets.

This meta-test fails loudly if the two ever diverge — the failure mode
the sidecar split was designed to make impossible. If you hand-edit one
fixture (mode (b) forward-merge of a local migration), you must edit
both in lockstep or this gate stops you.

Why a sidecar instead of augmenting `prod_columns.json` in place: the
repo already keeps per-column schema facets in their own files
(`prod_column_widths.json`, `prod_unique_indexes.json`). The typed
fixture follows that established convention. See
`audit/coach-77-phase-b-lite-approach-delta-gate-a-2026-05-14.md`.
"""
from __future__ import annotations

import json
import pathlib

_SCHEMA_DIR = (
    pathlib.Path(__file__).resolve().parent / "fixtures" / "schema"
)
_NAMES = _SCHEMA_DIR / "prod_columns.json"
_TYPES = _SCHEMA_DIR / "prod_column_types.json"


def _load(path: pathlib.Path):
    return json.loads(path.read_text())


def test_both_fixtures_exist():
    assert _NAMES.is_file(), f"missing {_NAMES}"
    assert _TYPES.is_file(), f"missing {_TYPES}"


def test_table_sets_identical():
    names = _load(_NAMES)
    types = _load(_TYPES)
    only_names = sorted(set(names) - set(types))
    only_types = sorted(set(types) - set(names))
    assert not only_names and not only_types, (
        "prod_columns.json and prod_column_types.json have diverged "
        "(table sets differ). Regenerate BOTH with the combined command "
        "in test_sql_columns_match_schema.py.\n"
        f"  only in prod_columns.json: {only_names}\n"
        f"  only in prod_column_types.json: {only_types}"
    )


def test_per_table_column_sets_identical():
    names = _load(_NAMES)
    types = _load(_TYPES)
    mismatches: list[str] = []
    for table in sorted(set(names) & set(types)):
        ncols = set(names[table])
        tcols = set(types[table])
        if ncols != tcols:
            mismatches.append(
                f"  {table}: only-in-names={sorted(ncols - tcols)} "
                f"only-in-types={sorted(tcols - ncols)}"
            )
    assert not mismatches, (
        "prod_columns.json and prod_column_types.json have diverged "
        "(per-table column sets differ). Regenerate BOTH with the "
        "combined command in test_sql_columns_match_schema.py.\n"
        + "\n".join(mismatches)
    )


def test_typed_fixture_values_are_nonempty_strings():
    """Every column maps to a non-empty data_type string — guards
    against a malformed regen (e.g. NULLs serialized as empty)."""
    types = _load(_TYPES)
    bad: list[str] = []
    for table, cols in types.items():
        for col, dtype in cols.items():
            if not isinstance(dtype, str) or not dtype:
                bad.append(f"  {table}.{col} = {dtype!r}")
    assert not bad, (
        "prod_column_types.json has columns with missing/empty "
        "data_type values:\n" + "\n".join(bad)
    )
