# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compliance_pb2 as compliance__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compliance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceAgentStub(object):
    """ComplianceAgent service handles communication from Go agents
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/compliance.ComplianceAgent/Register',
                request_serializer=compliance__pb2.RegisterRequest.SerializeToString,
                response_deserializer=compliance__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.ReportDrift = channel.stream_stream(
                '/compliance.ComplianceAgent/ReportDrift',
                request_serializer=compliance__pb2.DriftEvent.SerializeToString,
                response_deserializer=compliance__pb2.DriftAck.FromString,
                _registered_method=True)
        self.ReportHealing = channel.unary_unary(
                '/compliance.ComplianceAgent/ReportHealing',
                request_serializer=compliance__pb2.HealingResult.SerializeToString,
                response_deserializer=compliance__pb2.HealingAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/compliance.ComplianceAgent/Heartbeat',
                request_serializer=compliance__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=compliance__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportRMMStatus = channel.unary_unary(
                '/compliance.ComplianceAgent/ReportRMMStatus',
                request_serializer=compliance__pb2.RMMStatusReport.SerializeToString,
                response_deserializer=compliance__pb2.RMMAck.FromString,
                _registered_method=True)


class ComplianceAgentServicer(object):
    """ComplianceAgent service handles communication from Go agents
    """

    def Register(self, request, context):
        """Register a new agent with the appliance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDrift(self, request_iterator, context):
        """Report drift events (streaming from agent)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHealing(self, request, context):
        """Report healing results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRMMStatus(self, request, context):
        """Report RMM detection status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=compliance__pb2.RegisterRequest.FromString,
                    response_serializer=compliance__pb2.RegisterResponse.SerializeToString,
            ),
            'ReportDrift': grpc.stream_stream_rpc_method_handler(
                    servicer.ReportDrift,
                    request_deserializer=compliance__pb2.DriftEvent.FromString,
                    response_serializer=compliance__pb2.DriftAck.SerializeToString,
            ),
            'ReportHealing': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealing,
                    request_deserializer=compliance__pb2.HealingResult.FromString,
                    response_serializer=compliance__pb2.HealingAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=compliance__pb2.HeartbeatRequest.FromString,
                    response_serializer=compliance__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportRMMStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRMMStatus,
                    request_deserializer=compliance__pb2.RMMStatusReport.FromString,
                    response_serializer=compliance__pb2.RMMAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compliance.ComplianceAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('compliance.ComplianceAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceAgent(object):
    """ComplianceAgent service handles communication from Go agents
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compliance.ComplianceAgent/Register',
            compliance__pb2.RegisterRequest.SerializeToString,
            compliance__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDrift(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/compliance.ComplianceAgent/ReportDrift',
            compliance__pb2.DriftEvent.SerializeToString,
            compliance__pb2.DriftAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHealing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compliance.ComplianceAgent/ReportHealing',
            compliance__pb2.HealingResult.SerializeToString,
            compliance__pb2.HealingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compliance.ComplianceAgent/Heartbeat',
            compliance__pb2.HeartbeatRequest.SerializeToString,
            compliance__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRMMStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/compliance.ComplianceAgent/ReportRMMStatus',
            compliance__pb2.RMMStatusReport.SerializeToString,
            compliance__pb2.RMMAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
