// Session 207 Phase W1.1 — watchdog api_key auto-provisioning.
//
// On main-daemon startup, if /etc/msp-watchdog.yaml is absent or has an
// empty api_key field, POST /api/watchdog/bootstrap with the main
// daemon's bearer to mint a watchdog api_keys row. Write the plaintext
// key + computed appliance_id to the YAML file atomically. Trigger
// `systemctl restart appliance-daemon-watchdog` via systemd-run so the
// watchdog picks up the new config immediately.
//
// Runs exactly once per cold start, gated on file state so steady-state
// costs nothing. Failures are logged and soft — an uninitialized
// watchdog is a known state we can recover from; a wedged main daemon
// blocked on its own bootstrap would be worse.
package daemon

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"
)

const watchdogConfigPath = "/etc/msp-watchdog.yaml"

// BootstrapWatchdogIfNeeded is invoked once at cold start. Idempotent:
// no-op when the watchdog config already carries a non-empty api_key.
func (d *Daemon) BootstrapWatchdogIfNeeded(ctx context.Context) {
	if d.config == nil {
		return
	}
	if !watchdogConfigNeedsBootstrap(watchdogConfigPath) {
		log.Printf("[watchdog-bootstrap] config already populated, skipping")
		return
	}
	log.Printf("[watchdog-bootstrap] provisioning watchdog api_key")

	apiKey, watchdogAID, err := d.callWatchdogBootstrap(ctx)
	if err != nil {
		log.Printf("[watchdog-bootstrap] WARN: /api/watchdog/bootstrap failed: %v (watchdog stays idle until next main-daemon restart)", err)
		return
	}

	if err := writeWatchdogConfig(watchdogConfigPath, d.config.SiteID, watchdogAID, apiKey, d.config.APIEndpoint); err != nil {
		log.Printf("[watchdog-bootstrap] ERROR: writing %s failed: %v", watchdogConfigPath, err)
		return
	}

	if err := restartWatchdogService(ctx); err != nil {
		log.Printf("[watchdog-bootstrap] WARN: systemctl restart appliance-daemon-watchdog failed: %v (service will pick up on its own Restart= cycle)", err)
		return
	}
	log.Printf("[watchdog-bootstrap] OK: watchdog_aid=%s config written + service restarted", watchdogAID)
}

// watchdogConfigNeedsBootstrap returns true when the yaml file is
// absent, unreadable, or contains an empty `api_key:` field. Uses a
// cheap substring check — watchdog_api.py's idle-on-empty-key logic is
// the authoritative validator, this is just a fast gate.
func watchdogConfigNeedsBootstrap(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	text := string(data)
	// Very minimal check: look for an `api_key:` line whose value is
	// more than whitespace + quotes. Anything else = bootstrap needed.
	for _, line := range strings.Split(text, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "api_key:") {
			continue
		}
		val := strings.TrimSpace(strings.TrimPrefix(trimmed, "api_key:"))
		val = strings.Trim(val, "\"'")
		if val != "" {
			return false
		}
	}
	return true
}

type bootstrapResponse struct {
	SiteID      string `json:"site_id"`
	ApplianceID string `json:"appliance_id"`
	APIKey      string `json:"api_key"`
	APIEndpoint string `json:"api_endpoint"`
}

func (d *Daemon) callWatchdogBootstrap(ctx context.Context) (string, string, error) {
	url := strings.TrimRight(d.config.APIEndpoint, "/") + "/api/watchdog/bootstrap"
	// Backend uses bearer_aid as authoritative — body carries nothing
	// that can collide with or spoof the identity binding.
	body, _ := json.Marshal(map[string]string{})
	reqCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(reqCtx, "POST", url, bytes.NewReader(body))
	if err != nil {
		return "", "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+d.config.APIKey)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 300 {
		return "", "", fmt.Errorf("bootstrap HTTP %d: %s", resp.StatusCode, string(respBody))
	}
	var br bootstrapResponse
	if err := json.Unmarshal(respBody, &br); err != nil {
		return "", "", fmt.Errorf("parse response: %w", err)
	}
	if br.APIKey == "" || br.ApplianceID == "" {
		return "", "", fmt.Errorf("bootstrap response missing fields: %+v", br)
	}
	return br.APIKey, br.ApplianceID, nil
}

func writeWatchdogConfig(path, siteID, applianceID, apiKey, apiEndpoint string) error {
	tmp := path + ".tmp"
	content := fmt.Sprintf(
		"# Auto-generated by appliance-daemon at bootstrap.\n"+
			"# Do not edit by hand; re-run bootstrap to rotate the key.\n"+
			"site_id: %q\n"+
			"appliance_id: %q\n"+
			"api_key: %q\n"+
			"api_endpoint: %q\n",
		siteID, applianceID, apiKey, apiEndpoint,
	)
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("rename %s → %s: %w", tmp, path, err)
	}
	return nil
}

func restartWatchdogService(parent context.Context) error {
	// Use systemd-run to escape ProtectSystem=strict on this daemon's
	// unit — same pattern as boot_selfheal.removeStaleOverride.
	ctx, cancel := context.WithTimeout(parent, 20*time.Second)
	defer cancel()

	unitSuffix := fmt.Sprintf("%d", time.Now().UnixMilli())
	bash := "/run/current-system/sw/bin/bash"
	if _, err := os.Stat(bash); err != nil {
		bash = "/bin/bash"
	}

	cmd := exec.CommandContext(
		ctx,
		"systemd-run",
		"--unit=msp-watchdog-bootstrap-restart-"+unitSuffix,
		"--wait", "--pipe", "--collect",
		"--property=TimeoutStartSec=15",
		"--setenv=PATH=/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin",
		bash, "-c",
		"systemctl restart appliance-daemon-watchdog",
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemd-run: %w\n%s", err, string(out))
	}
	return nil
}
