# NATS Server Configuration
# Generated by Terraform for MSP Platform

# Server name
server_name: "${cluster_name}"

# Listen on all interfaces
listen: 0.0.0.0:4222

# Client connection settings
max_connections: 1000
max_payload: 1MB
max_pending: 10MB

# Authentication
%{ if enable_auth }
authorization {
  token: "${auth_token}"
}
%{ endif }

# JetStream (persistent messaging)
jetstream {
  store_dir: /var/lib/nats/jetstream
  max_memory_store: 1GB
  max_file_store: 10GB
}

# Clustering
cluster {
  name: "${cluster_name}"
  listen: 0.0.0.0:6222
  %{ if enable_auth }
  authorization {
    token: "${auth_token}"
  }
  %{ endif }
}

# Monitoring
http: 0.0.0.0:8222

# Logging
log_file: "/var/log/nats/nats-server.log"
log_size_limit: 100MB
max_traced_msg_len: 1024

# System account for monitoring
system_account: _SYS_

# Limits
max_control_line: 4096
write_deadline: "10s"
