-- Migration 097: WireGuard VPN management columns
-- Stores per-appliance WireGuard public keys and assigned VPN IPs

ALTER TABLE sites ADD COLUMN IF NOT EXISTS wg_pubkey TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS wg_ip TEXT;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS wg_connected_at TIMESTAMPTZ;

-- Index for IP allocation (find next available)
CREATE INDEX IF NOT EXISTS idx_sites_wg_ip ON sites (wg_ip) WHERE wg_ip IS NOT NULL;

COMMENT ON COLUMN sites.wg_pubkey IS 'WireGuard public key generated by the appliance (Curve25519)';
COMMENT ON COLUMN sites.wg_ip IS 'Assigned VPN IP on the 10.100.0.0/24 management network';
COMMENT ON COLUMN sites.wg_connected_at IS 'Last time WireGuard handshake was detected';
