-- Migration 158: Pre-boot install telemetry.
--
-- Installer ISO POSTs an install report BEFORE the installed system has
-- ever checked in. This gives us visibility into which physical boxes
-- started installing, which completed, which failed, and where.
--
-- Round Table Session 205: "A zombie installer that sits silently for
-- 18 hours is not a product. Pre-boot telemetry lets us see install
-- failures the moment they happen, not after a customer complains."

CREATE TABLE IF NOT EXISTS install_reports (
    id SERIAL PRIMARY KEY,
    installer_id UUID NOT NULL UNIQUE,    -- one row per install attempt
    mac_address VARCHAR(17),
    serial_number VARCHAR(100),
    bios_vendor VARCHAR(100),
    bios_version VARCHAR(100),
    product_name VARCHAR(200),            -- e.g. "HP t740 Thin Client"
    cpu_model VARCHAR(200),
    memory_gb INTEGER,
    -- Storage
    drive_path VARCHAR(50),               -- /dev/sda, /dev/nvme0n1, /dev/mmcblk0
    drive_model VARCHAR(200),
    drive_size_gb INTEGER,
    drive_smart_status VARCHAR(20),       -- PASSED / FAILED / UNKNOWN
    drive_is_removable BOOLEAN,
    -- Network
    network_iface VARCHAR(20),
    network_mac VARCHAR(17),
    network_ip INET,
    network_gateway INET,
    network_dns TEXT[],
    network_mtu INTEGER,
    network_dhcp_success BOOLEAN,
    network_api_reachable BOOLEAN,
    network_ntp_synced BOOLEAN,
    -- Timing
    install_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    install_completed_at TIMESTAMPTZ,
    install_duration_s INTEGER,
    -- Outcome
    install_success BOOLEAN,
    error_step VARCHAR(50),               -- hw_probe, net_check, dd_write, verify, etc
    error_message TEXT,
    warnings TEXT[],                      -- non-fatal issues to record
    -- Metadata
    installer_version VARCHAR(20),
    image_sha256 VARCHAR(64),             -- the raw image the installer wrote
    verify_sha256 VARCHAR(64),            -- what we read back for verification
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_install_reports_mac ON install_reports(mac_address);
CREATE INDEX IF NOT EXISTS idx_install_reports_started ON install_reports(install_started_at DESC);
CREATE INDEX IF NOT EXISTS idx_install_reports_success ON install_reports(install_success, install_started_at DESC);

COMMENT ON TABLE install_reports IS
  'Pre-boot telemetry from the OsirisCare installer ISO. One row per install attempt. '
  'Populated by the installer BEFORE the installed system has ever checked in.';

COMMENT ON COLUMN install_reports.installer_id IS
  'UUID generated by the installer on USB boot. Unique per install attempt. '
  'Used as primary identifier since MAC may not be available pre-network.';

COMMENT ON COLUMN install_reports.error_step IS
  'Phase where the install failed. Known values: hw_probe, net_check, ntp_sync, '
  'api_reach, image_decompress, dd_write, verify_readback, bootloader_install, complete.';
