// OsirisCare Compliance Agent gRPC Service
//
// This defines the communication protocol between Go Agents on Windows
// workstations and the Python Compliance Agent on the NixOS appliance.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.3
// source: compliance.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplianceAgent_Register_FullMethodName        = "/compliance.ComplianceAgent/Register"
	ComplianceAgent_ReportDrift_FullMethodName     = "/compliance.ComplianceAgent/ReportDrift"
	ComplianceAgent_ReportHealing_FullMethodName   = "/compliance.ComplianceAgent/ReportHealing"
	ComplianceAgent_Heartbeat_FullMethodName       = "/compliance.ComplianceAgent/Heartbeat"
	ComplianceAgent_ReportRMMStatus_FullMethodName = "/compliance.ComplianceAgent/ReportRMMStatus"
)

// ComplianceAgentClient is the client API for ComplianceAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ComplianceAgent service handles communication from Go agents
type ComplianceAgentClient interface {
	// Register a new agent with the appliance
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Report drift events (streaming from agent)
	ReportDrift(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DriftEvent, DriftAck], error)
	// Report healing results
	ReportHealing(ctx context.Context, in *HealingResult, opts ...grpc.CallOption) (*HealingAck, error)
	// Send heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Report RMM detection status
	ReportRMMStatus(ctx context.Context, in *RMMStatusReport, opts ...grpc.CallOption) (*RMMAck, error)
}

type complianceAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewComplianceAgentClient(cc grpc.ClientConnInterface) ComplianceAgentClient {
	return &complianceAgentClient{cc}
}

func (c *complianceAgentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ComplianceAgent_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceAgentClient) ReportDrift(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DriftEvent, DriftAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComplianceAgent_ServiceDesc.Streams[0], ComplianceAgent_ReportDrift_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DriftEvent, DriftAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComplianceAgent_ReportDriftClient = grpc.BidiStreamingClient[DriftEvent, DriftAck]

func (c *complianceAgentClient) ReportHealing(ctx context.Context, in *HealingResult, opts ...grpc.CallOption) (*HealingAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealingAck)
	err := c.cc.Invoke(ctx, ComplianceAgent_ReportHealing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceAgentClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ComplianceAgent_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceAgentClient) ReportRMMStatus(ctx context.Context, in *RMMStatusReport, opts ...grpc.CallOption) (*RMMAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RMMAck)
	err := c.cc.Invoke(ctx, ComplianceAgent_ReportRMMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplianceAgentServer is the server API for ComplianceAgent service.
// All implementations must embed UnimplementedComplianceAgentServer
// for forward compatibility.
//
// ComplianceAgent service handles communication from Go agents
type ComplianceAgentServer interface {
	// Register a new agent with the appliance
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Report drift events (streaming from agent)
	ReportDrift(grpc.BidiStreamingServer[DriftEvent, DriftAck]) error
	// Report healing results
	ReportHealing(context.Context, *HealingResult) (*HealingAck, error)
	// Send heartbeat
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Report RMM detection status
	ReportRMMStatus(context.Context, *RMMStatusReport) (*RMMAck, error)
	mustEmbedUnimplementedComplianceAgentServer()
}

// UnimplementedComplianceAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplianceAgentServer struct{}

func (UnimplementedComplianceAgentServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedComplianceAgentServer) ReportDrift(grpc.BidiStreamingServer[DriftEvent, DriftAck]) error {
	return status.Error(codes.Unimplemented, "method ReportDrift not implemented")
}
func (UnimplementedComplianceAgentServer) ReportHealing(context.Context, *HealingResult) (*HealingAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealing not implemented")
}
func (UnimplementedComplianceAgentServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedComplianceAgentServer) ReportRMMStatus(context.Context, *RMMStatusReport) (*RMMAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportRMMStatus not implemented")
}
func (UnimplementedComplianceAgentServer) mustEmbedUnimplementedComplianceAgentServer() {}
func (UnimplementedComplianceAgentServer) testEmbeddedByValue()                         {}

// UnsafeComplianceAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplianceAgentServer will
// result in compilation errors.
type UnsafeComplianceAgentServer interface {
	mustEmbedUnimplementedComplianceAgentServer()
}

func RegisterComplianceAgentServer(s grpc.ServiceRegistrar, srv ComplianceAgentServer) {
	// If the following call panics, it indicates UnimplementedComplianceAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplianceAgent_ServiceDesc, srv)
}

func _ComplianceAgent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceAgentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceAgent_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceAgentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceAgent_ReportDrift_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComplianceAgentServer).ReportDrift(&grpc.GenericServerStream[DriftEvent, DriftAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComplianceAgent_ReportDriftServer = grpc.BidiStreamingServer[DriftEvent, DriftAck]

func _ComplianceAgent_ReportHealing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealingResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceAgentServer).ReportHealing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceAgent_ReportHealing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceAgentServer).ReportHealing(ctx, req.(*HealingResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceAgent_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceAgentServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceAgent_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceAgentServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceAgent_ReportRMMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RMMStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceAgentServer).ReportRMMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceAgent_ReportRMMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceAgentServer).ReportRMMStatus(ctx, req.(*RMMStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplianceAgent_ServiceDesc is the grpc.ServiceDesc for ComplianceAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplianceAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compliance.ComplianceAgent",
	HandlerType: (*ComplianceAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ComplianceAgent_Register_Handler,
		},
		{
			MethodName: "ReportHealing",
			Handler:    _ComplianceAgent_ReportHealing_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ComplianceAgent_Heartbeat_Handler,
		},
		{
			MethodName: "ReportRMMStatus",
			Handler:    _ComplianceAgent_ReportRMMStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportDrift",
			Handler:       _ComplianceAgent_ReportDrift_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "compliance.proto",
}
