name: Update Flake Dependencies

on:
  schedule:
    # Run weekly on Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: |
          echo "Updating flake.lock..."
          nix flake update --commit-lock-file

          # Get list of updated inputs
          git show HEAD --stat > update-summary.txt

      - name: Check if updates available
        id: check_updates
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No updates available"
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "Updates available"
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and test with updates
        if: steps.check_updates.outputs.has_updates == 'true'
        run: |
          echo "Building with updated dependencies..."
          nix flake check --show-trace

          echo "Building container..."
          nix build .#container --print-build-logs

      - name: Create Pull Request
        if: steps.check_updates.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update flake dependencies'
          title: 'Automated flake dependency update'
          body: |
            ## Automated Flake Update

            This PR updates the flake.lock file with the latest upstream versions.

            ### Changes

            ```
            $(cat update-summary.txt)
            ```

            ### Testing

            - ✅ `nix flake check` passed
            - ✅ Container build successful

            ### Security Review Required

            Please review the updates for:
            - Breaking changes in NixOS modules
            - Security advisories for updated packages
            - HIPAA baseline compatibility

            ### Merge Checklist

            - [ ] Review changelog for breaking changes
            - [ ] Test deployment in lab environment
            - [ ] Verify compliance checks still pass
            - [ ] Update baseline version if needed

            ---

            *This PR was automatically generated by the update-flake workflow*
          branch: automated-flake-update
          delete-branch: true
          labels: |
            dependencies
            automated
